# Generated by Django 5.0.6 on 2024-07-08 00:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('math', 'Math'), ('language', 'Language'), ('programming', 'Programming'), ('arts', 'Arts'), ('grammatical', 'Grammatical')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_per_session', models.IntegerField(blank=True, null=True)),
                ('duration_in_minutes', models.IntegerField(blank=True, null=True)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/classes')),
                ('video_360p', models.FileField(blank=True, null=True, upload_to='uploads/classes')),
                ('video_480p', models.FileField(blank=True, null=True, upload_to='uploads/classes')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to='uploads/classes')),
                ('video_1080p', models.FileField(blank=True, null=True, upload_to='uploads/classes')),
                ('external_video_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subtitles', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
