# Generated by Django 5.0.6 on 2024-07-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/classes'),
        ),
    ]
