# Generated by Django 5.0.6 on 2024-07-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_video_480p'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subtitles',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
